import { User } from '../models/user.models';
import { UserVerifyStatus } from '../utils/user.utils';

const Users: User[] = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    password: 'password123',
    isVerified: UserVerifyStatus.verified,
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    password: 'securepass456',
    isVerified: UserVerifyStatus.unverified,
  },
  {
    id: 3,
    firstName: 'Alice',
    lastName: 'Johnson',
    email: 'alice.johnson@example.com',
    password: 'mypassword789',
    isVerified: UserVerifyStatus.verified,
  },
  {
    id: 4,
    firstName: 'Bob',
    lastName: 'Brown',
    email: 'bob.brown@example.com',
    password: 'bobsecurepass101',
    isVerified: UserVerifyStatus.unverified,
  },
  {
    id: 5,
    firstName: 'Charlie',
    lastName: 'Davis',
    email: 'charlie.davis@example.com',
    password: 'charliepass202',
    isVerified: UserVerifyStatus.verified,
  },
  {
    id: 6,
    firstName: 'David',
    lastName: 'Miller',
    email: 'david.miller@example.com',
    password: 'davidsafe789',
    isVerified: UserVerifyStatus.unverified,
  },
  {
    id: 7,
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma.wilson@example.com',
    password: 'emmaSecret555',
    isVerified: UserVerifyStatus.verified,
  },
  {
    id: 8,
    firstName: 'Lucas',
    lastName: 'Anderson',
    email: 'lucas.anderson@example.com',
    password: 'lucaspass900',
    isVerified: UserVerifyStatus.unverified,
  },
  {
    id: 9,
    firstName: 'Mia',
    lastName: 'Thomas',
    email: 'mia.thomas@example.com',
    password: 'miaPassword777',
    isVerified: UserVerifyStatus.verified,
  },
  {
    id: 10,
    firstName: 'Noah',
    lastName: 'Moore',
    email: 'noah.moore@example.com',
    password: 'noahpass666',
    isVerified: UserVerifyStatus.unverified,
  },
  {
    id: 11,
    firstName: 'Olivia',
    lastName: 'Taylor',
    email: 'olivia.taylor@example.com',
    password: 'oliviaSecure123',
    isVerified: UserVerifyStatus.verified,
  },
  {
    id: 12,
    firstName: 'Sophia',
    lastName: 'Martinez',
    email: 'sophia.martinez@example.com',
    password: 'sophiaStrong888',
    isVerified: UserVerifyStatus.unverified,
  },
  {
    id: 13,
    firstName: 'William',
    lastName: 'Garcia',
    email: 'william.garcia@example.com',
    password: 'willPass234',
    isVerified: UserVerifyStatus.verified,
  },
  {
    id: 14,
    firstName: 'Ava',
    lastName: 'Hernandez',
    email: 'ava.hernandez@example.com',
    password: 'avaSafe000',
    isVerified: UserVerifyStatus.unverified,
  },
  {
    id: 15,
    firstName: 'James',
    lastName: 'Lopez',
    email: 'james.lopez@example.com',
    password: 'jamesSecure909',
    isVerified: UserVerifyStatus.verified,
  },
  {
    id: 16,
    firstName: 'Isabella',
    lastName: 'Gonzalez',
    email: 'isabella.gonzalez@example.com',
    password: 'bellaPass888',
    isVerified: UserVerifyStatus.unverified,
  },
  {
    id: 17,
    firstName: 'Benjamin',
    lastName: 'Perez',
    email: 'benjamin.perez@example.com',
    password: 'benSecure123',
    isVerified: UserVerifyStatus.verified,
  },
  {
    id: 18,
    firstName: 'Elijah',
    lastName: 'Clark',
    email: 'elijah.clark@example.com',
    password: 'elijahStrong999',
    isVerified: UserVerifyStatus.unverified,
  },
  {
    id: 19,
    firstName: 'Liam',
    lastName: 'Young',
    email: 'liam.young@example.com',
    password: 'liamSafe234',
    isVerified: UserVerifyStatus.verified,
  },
  {
    id: 20,
    firstName: 'Charlotte',
    lastName: 'King',
    email: 'charlotte.king@example.com',
    password: 'charlottePass444',
    isVerified: UserVerifyStatus.unverified,
  },
];

export { Users };
