services:
  postgres:
    image: postgres:16
    container_name: project1_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project1_db
    ports:
      - "5432:5432"
    volumes:
      - project1_database_volume:/var/lib/postgresql/data
    networks:
      - project1_network

  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: project1_container
    ports:
      - 8000:8000
    networks:
      - project1_container_network
    volumes:
      - "./:usr/src/app"
networks:
  project1_network:
    name: project1_network
    driver: bridge
volumes:
  project1_database_volume:
